name: Canary

on:
  push:
    branches:
      - master

jobs:
  canary:
    name: Publish canary to NPM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jsxstyle
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run jest
        run: yarn run test
      - name: Run karma
        run: yarn --cwd "tests" run karma-headless-chrome
        env:
          CI: true
          TZ: 'America/Los_Angeles'
      - name: Configure NPM
        run: |
          npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          npm set username ${{ secrets.NPM_USERNAME }}
          npm set email ${{ secrets.NPM_EMAIL }}
      - name: Publish
        run: npx lerna publish --canary --preid canary --dist-tag next --yes --no-git-reset --force-publish "*"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
